services:
  postgres:
    container_name: "bighomework-db"
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=big_homework'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=document_user'
    ports:
      - '6432:5432'